---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
name: Haha
on: push

jobs:
  build:
    name: Hha
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dis: ['zulu', 'liberica']
        pac: ['jdk+fx', 'jre+fx']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.dis }}
          java-version: '17'
          java-package: ${{ matrix.pac }}
